model_list:
  - model_name: cohere_command_latest
    litellm_params:
      model: oci/cohere.command-latest
      oci_serving_mode: "ON_DEMAND"
      oci_compartment_id: "##TF_VAR_compartment_ocid##"
      oci_region: "##TF_VAR_region##"
      oci_user: "##TF_VAR_user_ocid##"
      oci_tenancy: "##TF_VAR_tenancy_ocid##"
      oci_fingerprint: "##OCI_FINGER_PRINT##"
      oci_key: "##OCI_KEY##"
